version: '3.9'

services:
  web:
    build: .
    command: gunicorn planetarium_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media:/app/media
      - static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  media:
  static: