# Generated by Django 5.2.1 on 2025-05-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0003_showtheme_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat', 'show_session')},
        ),
    ]
